export type HangmanCategory = "common" | "animals" | "food" | "places" | "tech" | "movies" | "expert";
export const CATEGORY_LABELS: Record<HangmanCategory, string> = {
  common: "Common",
  animals: "Animals",
  food: "Food",
  places: "Places",
  tech: "Tech",
  movies: "Movies",
  expert: "Expert",
};

const COMMON = "ANCHOR APPLE ASTEROID AVENUE BANJO BASKET BEACON BIRTHDAY BLANKET BOTTLE BRIDGE CANDLE CAPTAIN CARTOON CASTLE CHEESE CHIMNEY CIRCUS COMPUTER COUNTRY CRYSTAL DELIGHT DIAMOND DRAGON DREAM EAGLE FAMILY FANTASY FESTIVE FOREST FORTUNE FROZEN GADGET GALAXY GUITAR HAMMER HARBOR HARMONY HEART HOLIDAY HORIZON IMPACT INVENT ISLAND JOURNAL JUSTICE KETTLE KINGDOM KNIGHT LANTERN LEGEND LIBRARY LIGHTNING MAGNET MIRROR MISSION MORNING MOUNTAIN MUSEUM MYSTERY OCEAN ORBIT PALACE PARADISE PHOENIX PIRATE PLANET PUZZLE RAINBOW ROBOT ROCKET SAILOR SAPPHIRE SCISSORS SECRET SHADOW SIGNAL SILVER SOLAR SPONGE STADIUM STORM SUMMER SUNRISE TABLET TEMPLE THUNDER TIGER TRAVEL TREASURE TROPHY TUNNEL TWILIGHT UMBRELLA UNICORN UNIVERSE VALLEY VICTORY VIOLIN VOLCANO VOYAGE WATERFALL WEDDING WHISPER WILDLIFE WINTER WIZARD".split(" ");
const ANIMALS = "ELEPHANT GIRAFFE PENGUIN DOLPHIN OCTOPUS BUTTERFLY CROCODILE HEDGEHOG KANGAROO PORCUPINE RACCOON SQUIRREL CHEETAH GORILLA RHINOCEROS HIPPOPOTAMUS PEACOCK FLAMINGO ALBATROSS COBRA IGUANA TARANTULA SCORPION JELLYFISH STARFISH SEAHORSE PUFFIN ARMADILLO PLATYPUS LEMUR MEERKAT OCELOT TAPIR BEAVER WOMBAT CAPYBARA NARWHAL ORCA WALRUS LYNX MOOSE CARIBOU BISON ZEBRA OSTRICH SLOTH PANGOLIN PORPOISE WALLABY YAK".split(" ");
const FOOD = "PIZZA BURGER PASTA SUSHI TACOS RAMEN BURRITO LASAGNA RISOTTO PAELLA DUMPLINGS PANCAKES WAFFLES CROISSANT BAGEL CUPCAKE DONUT BROWNIE MUFFIN CHEESECAKE TIRAMISU MACARON GELATO PUDDING POPCORN SALMON SHRIMP LOBSTER CALAMARI OYSTER ARTICHOKE ASPARAGUS BROCCOLI ZUCCHINI EGGPLANT POTATO TOMATO AVOCADO MANGO PAPAYA PINEAPPLE COCONUT STRAWBERRY BLUEBERRY RASPBERRY WATERMELON CINNAMON GINGER WASABI SRIRACHA".split(" ");
const PLACES = "TOKYO PARIS LONDON SYDNEY MOSCOW BERLIN MADRID ATHENS CAIRO LISBON DUBLIN PRAGUE VIENNA REYKJAVIK HELSINKI COPENHAGEN AMSTERDAM BARCELONA FLORENCE VENICE SANTORINI MARRAKESH NAIROBI BANGKOK JAKARTA SINGAPORE HONOLULU REYKJAVIK ANTARCTICA AMAZON SAHARA HIMALAYAS GALAPAGOS PATAGONIA YOSEMITE MACHU PETRA ANGKOR STONEHENGE COLOSSEUM ACROPOLIS HOLLYWOOD MANHATTAN BROOKLYN EVEREST KILIMANJARO ATACAMA SERENGETI BORNEO MADAGASCAR".split(" ");
const TECH = "ALGORITHM DATABASE NETWORK INTERNET WEBSITE BROWSER PROGRAM SOFTWARE HARDWARE KEYBOARD MONITOR PIXEL CIRCUIT TRANSISTOR PROCESSOR MEMORY STORAGE BANDWIDTH PROTOCOL ENCRYPTION FIREWALL VIRUS MALWARE BACKUP COMPILER JAVASCRIPT TYPESCRIPT PYTHON FRAMEWORK LIBRARY PACKAGE MODULE FUNCTION VARIABLE CONSTANT BOOLEAN INTEGER STRING ARRAY OBJECT POINTER RECURSION FRONTEND BACKEND CLOUD SERVER CLIENT GITHUB DOCKER REACT".split(" ");
const MOVIES = "INCEPTION GLADIATOR AVATAR TITANIC MATRIX ALIENS PREDATOR TERMINATOR ROCKY TWILIGHT WHIPLASH PARASITE GOODFELLAS CASABLANCA RASHOMON SEVEN AMELIE FARGO MEMENTO TRAINSPOTTING JOKER COCO MOANA TANGLED FROZEN ZOOTOPIA RATATOUILLE WALL ENCANTO TURNING SHREK ALADDIN MULAN HERCULES TARZAN POCAHONTAS MOULIN GREASE CHICAGO HAIRSPRAY DRACULA NOSFERATU PSYCHO HALLOWEEN POLTERGEIST EXORCIST CARRIE SHINING".split(" ");
const EXPERT = "JUXTAPOSE QUIXOTIC ZEPHYR LUGUBRIOUS PERSPICACIOUS SESQUIPEDALIAN PNEUMONOULTRA SUPERCALIFRAGILISTIC ANTIDISESTABLISHMENT FLOCCINAUCINIHILIPILIFICATION PSEUDOPSEUDOHYPOPARA HONORIFICABILITUDINITATIBUS PERTHRO ETHRO ALGIZ TIWAZ EHWAZ MANNAZ INGWAZ DAGAZ OTHALA ANSUZ ALGIZ JERA SOWILO RAIDHO HAGALAZ".split(" ").filter((w) => w.length >= 5);

export function getWords(cat: HangmanCategory): string[] {
  return { common: COMMON, animals: ANIMALS, food: FOOD, places: PLACES, tech: TECH, movies: MOVIES, expert: EXPERT }[cat];
}
